baseURL = "http://wondering.monster/"
languageCode = "en-gb"
title = "Wondering Monster"
theme = "gramarye"
paginate = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true